// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gwangyi/fsx/contextual (interfaces: FS,ReadFileFS,WriterFS,ChangeFS,ReadDirFS,DirFS,MkdirAllFS,RemoveAllFS,RenameFS,StatFS,ReadLinkFS,SymlinkFS,LchownFS,TruncateFS,WriteFileFS)
//
// Generated by this command:
//
//	mockgen -destination ../mockfs/contextual/mockfs.go -package cmockfs . FS,ReadFileFS,WriterFS,ChangeFS,ReadDirFS,DirFS,MkdirAllFS,RemoveAllFS,RenameFS,StatFS,ReadLinkFS,SymlinkFS,LchownFS,TruncateFS,WriteFileFS
//

// Package cmockfs is a generated GoMock package.
package cmockfs

import (
	context "context"
	fs "io/fs"
	reflect "reflect"
	time "time"

	contextual "github.com/gwangyi/fsx/contextual"
	gomock "go.uber.org/mock/gomock"
)

// MockFS is a mock of FS interface.
type MockFS struct {
	ctrl     *gomock.Controller
	recorder *MockFSMockRecorder
	isgomock struct{}
}

// MockFSMockRecorder is the mock recorder for MockFS.
type MockFSMockRecorder struct {
	mock *MockFS
}

// NewMockFS creates a new mock instance.
func NewMockFS(ctrl *gomock.Controller) *MockFS {
	mock := &MockFS{ctrl: ctrl}
	mock.recorder = &MockFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFS) EXPECT() *MockFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockFS) Open(ctx context.Context, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockFSMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockFS)(nil).Open), ctx, name)
}

// MockReadFileFS is a mock of ReadFileFS interface.
type MockReadFileFS struct {
	ctrl     *gomock.Controller
	recorder *MockReadFileFSMockRecorder
	isgomock struct{}
}

// MockReadFileFSMockRecorder is the mock recorder for MockReadFileFS.
type MockReadFileFSMockRecorder struct {
	mock *MockReadFileFS
}

// NewMockReadFileFS creates a new mock instance.
func NewMockReadFileFS(ctrl *gomock.Controller) *MockReadFileFS {
	mock := &MockReadFileFS{ctrl: ctrl}
	mock.recorder = &MockReadFileFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadFileFS) EXPECT() *MockReadFileFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockReadFileFS) Open(ctx context.Context, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockReadFileFSMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockReadFileFS)(nil).Open), ctx, name)
}

// ReadFile mocks base method.
func (m *MockReadFileFS) ReadFile(ctx context.Context, name string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", ctx, name)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockReadFileFSMockRecorder) ReadFile(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockReadFileFS)(nil).ReadFile), ctx, name)
}

// MockWriterFS is a mock of WriterFS interface.
type MockWriterFS struct {
	ctrl     *gomock.Controller
	recorder *MockWriterFSMockRecorder
	isgomock struct{}
}

// MockWriterFSMockRecorder is the mock recorder for MockWriterFS.
type MockWriterFSMockRecorder struct {
	mock *MockWriterFS
}

// NewMockWriterFS creates a new mock instance.
func NewMockWriterFS(ctrl *gomock.Controller) *MockWriterFS {
	mock := &MockWriterFS{ctrl: ctrl}
	mock.recorder = &MockWriterFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriterFS) EXPECT() *MockWriterFSMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWriterFS) Create(ctx context.Context, name string) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWriterFSMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWriterFS)(nil).Create), ctx, name)
}

// Open mocks base method.
func (m *MockWriterFS) Open(ctx context.Context, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockWriterFSMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockWriterFS)(nil).Open), ctx, name)
}

// OpenFile mocks base method.
func (m *MockWriterFS) OpenFile(ctx context.Context, name string, flag int, mode fs.FileMode) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", ctx, name, flag, mode)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockWriterFSMockRecorder) OpenFile(ctx, name, flag, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockWriterFS)(nil).OpenFile), ctx, name, flag, mode)
}

// Remove mocks base method.
func (m *MockWriterFS) Remove(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWriterFSMockRecorder) Remove(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWriterFS)(nil).Remove), ctx, name)
}

// MockChangeFS is a mock of ChangeFS interface.
type MockChangeFS struct {
	ctrl     *gomock.Controller
	recorder *MockChangeFSMockRecorder
	isgomock struct{}
}

// MockChangeFSMockRecorder is the mock recorder for MockChangeFS.
type MockChangeFSMockRecorder struct {
	mock *MockChangeFS
}

// NewMockChangeFS creates a new mock instance.
func NewMockChangeFS(ctrl *gomock.Controller) *MockChangeFS {
	mock := &MockChangeFS{ctrl: ctrl}
	mock.recorder = &MockChangeFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangeFS) EXPECT() *MockChangeFSMockRecorder {
	return m.recorder
}

// Chmod mocks base method.
func (m *MockChangeFS) Chmod(ctx context.Context, name string, mode fs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chmod", ctx, name, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chmod indicates an expected call of Chmod.
func (mr *MockChangeFSMockRecorder) Chmod(ctx, name, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chmod", reflect.TypeOf((*MockChangeFS)(nil).Chmod), ctx, name, mode)
}

// Chown mocks base method.
func (m *MockChangeFS) Chown(ctx context.Context, name, owner, group string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chown", ctx, name, owner, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chown indicates an expected call of Chown.
func (mr *MockChangeFSMockRecorder) Chown(ctx, name, owner, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chown", reflect.TypeOf((*MockChangeFS)(nil).Chown), ctx, name, owner, group)
}

// Chtimes mocks base method.
func (m *MockChangeFS) Chtimes(ctx context.Context, name string, atime, ctime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chtimes", ctx, name, atime, ctime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chtimes indicates an expected call of Chtimes.
func (mr *MockChangeFSMockRecorder) Chtimes(ctx, name, atime, ctime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chtimes", reflect.TypeOf((*MockChangeFS)(nil).Chtimes), ctx, name, atime, ctime)
}

// Create mocks base method.
func (m *MockChangeFS) Create(ctx context.Context, name string) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockChangeFSMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockChangeFS)(nil).Create), ctx, name)
}

// Open mocks base method.
func (m *MockChangeFS) Open(ctx context.Context, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockChangeFSMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockChangeFS)(nil).Open), ctx, name)
}

// OpenFile mocks base method.
func (m *MockChangeFS) OpenFile(ctx context.Context, name string, flag int, mode fs.FileMode) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", ctx, name, flag, mode)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockChangeFSMockRecorder) OpenFile(ctx, name, flag, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockChangeFS)(nil).OpenFile), ctx, name, flag, mode)
}

// Remove mocks base method.
func (m *MockChangeFS) Remove(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockChangeFSMockRecorder) Remove(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockChangeFS)(nil).Remove), ctx, name)
}

// MockReadDirFS is a mock of ReadDirFS interface.
type MockReadDirFS struct {
	ctrl     *gomock.Controller
	recorder *MockReadDirFSMockRecorder
	isgomock struct{}
}

// MockReadDirFSMockRecorder is the mock recorder for MockReadDirFS.
type MockReadDirFSMockRecorder struct {
	mock *MockReadDirFS
}

// NewMockReadDirFS creates a new mock instance.
func NewMockReadDirFS(ctrl *gomock.Controller) *MockReadDirFS {
	mock := &MockReadDirFS{ctrl: ctrl}
	mock.recorder = &MockReadDirFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadDirFS) EXPECT() *MockReadDirFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockReadDirFS) Open(ctx context.Context, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockReadDirFSMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockReadDirFS)(nil).Open), ctx, name)
}

// ReadDir mocks base method.
func (m *MockReadDirFS) ReadDir(ctx context.Context, name string) ([]fs.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", ctx, name)
	ret0, _ := ret[0].([]fs.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockReadDirFSMockRecorder) ReadDir(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockReadDirFS)(nil).ReadDir), ctx, name)
}

// MockDirFS is a mock of DirFS interface.
type MockDirFS struct {
	ctrl     *gomock.Controller
	recorder *MockDirFSMockRecorder
	isgomock struct{}
}

// MockDirFSMockRecorder is the mock recorder for MockDirFS.
type MockDirFSMockRecorder struct {
	mock *MockDirFS
}

// NewMockDirFS creates a new mock instance.
func NewMockDirFS(ctrl *gomock.Controller) *MockDirFS {
	mock := &MockDirFS{ctrl: ctrl}
	mock.recorder = &MockDirFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirFS) EXPECT() *MockDirFSMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDirFS) Create(ctx context.Context, name string) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDirFSMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDirFS)(nil).Create), ctx, name)
}

// Mkdir mocks base method.
func (m *MockDirFS) Mkdir(ctx context.Context, name string, perm fs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mkdir", ctx, name, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mkdir indicates an expected call of Mkdir.
func (mr *MockDirFSMockRecorder) Mkdir(ctx, name, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mkdir", reflect.TypeOf((*MockDirFS)(nil).Mkdir), ctx, name, perm)
}

// Open mocks base method.
func (m *MockDirFS) Open(ctx context.Context, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockDirFSMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockDirFS)(nil).Open), ctx, name)
}

// OpenFile mocks base method.
func (m *MockDirFS) OpenFile(ctx context.Context, name string, flag int, mode fs.FileMode) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", ctx, name, flag, mode)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockDirFSMockRecorder) OpenFile(ctx, name, flag, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockDirFS)(nil).OpenFile), ctx, name, flag, mode)
}

// ReadDir mocks base method.
func (m *MockDirFS) ReadDir(ctx context.Context, name string) ([]fs.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", ctx, name)
	ret0, _ := ret[0].([]fs.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockDirFSMockRecorder) ReadDir(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockDirFS)(nil).ReadDir), ctx, name)
}

// Remove mocks base method.
func (m *MockDirFS) Remove(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockDirFSMockRecorder) Remove(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockDirFS)(nil).Remove), ctx, name)
}

// MockMkdirAllFS is a mock of MkdirAllFS interface.
type MockMkdirAllFS struct {
	ctrl     *gomock.Controller
	recorder *MockMkdirAllFSMockRecorder
	isgomock struct{}
}

// MockMkdirAllFSMockRecorder is the mock recorder for MockMkdirAllFS.
type MockMkdirAllFSMockRecorder struct {
	mock *MockMkdirAllFS
}

// NewMockMkdirAllFS creates a new mock instance.
func NewMockMkdirAllFS(ctrl *gomock.Controller) *MockMkdirAllFS {
	mock := &MockMkdirAllFS{ctrl: ctrl}
	mock.recorder = &MockMkdirAllFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMkdirAllFS) EXPECT() *MockMkdirAllFSMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMkdirAllFS) Create(ctx context.Context, name string) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMkdirAllFSMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMkdirAllFS)(nil).Create), ctx, name)
}

// Mkdir mocks base method.
func (m *MockMkdirAllFS) Mkdir(ctx context.Context, name string, perm fs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mkdir", ctx, name, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mkdir indicates an expected call of Mkdir.
func (mr *MockMkdirAllFSMockRecorder) Mkdir(ctx, name, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mkdir", reflect.TypeOf((*MockMkdirAllFS)(nil).Mkdir), ctx, name, perm)
}

// MkdirAll mocks base method.
func (m *MockMkdirAllFS) MkdirAll(ctx context.Context, name string, perm fs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", ctx, name, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockMkdirAllFSMockRecorder) MkdirAll(ctx, name, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockMkdirAllFS)(nil).MkdirAll), ctx, name, perm)
}

// Open mocks base method.
func (m *MockMkdirAllFS) Open(ctx context.Context, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockMkdirAllFSMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockMkdirAllFS)(nil).Open), ctx, name)
}

// OpenFile mocks base method.
func (m *MockMkdirAllFS) OpenFile(ctx context.Context, name string, flag int, mode fs.FileMode) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", ctx, name, flag, mode)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockMkdirAllFSMockRecorder) OpenFile(ctx, name, flag, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockMkdirAllFS)(nil).OpenFile), ctx, name, flag, mode)
}

// ReadDir mocks base method.
func (m *MockMkdirAllFS) ReadDir(ctx context.Context, name string) ([]fs.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", ctx, name)
	ret0, _ := ret[0].([]fs.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockMkdirAllFSMockRecorder) ReadDir(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockMkdirAllFS)(nil).ReadDir), ctx, name)
}

// Remove mocks base method.
func (m *MockMkdirAllFS) Remove(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockMkdirAllFSMockRecorder) Remove(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockMkdirAllFS)(nil).Remove), ctx, name)
}

// MockRemoveAllFS is a mock of RemoveAllFS interface.
type MockRemoveAllFS struct {
	ctrl     *gomock.Controller
	recorder *MockRemoveAllFSMockRecorder
	isgomock struct{}
}

// MockRemoveAllFSMockRecorder is the mock recorder for MockRemoveAllFS.
type MockRemoveAllFSMockRecorder struct {
	mock *MockRemoveAllFS
}

// NewMockRemoveAllFS creates a new mock instance.
func NewMockRemoveAllFS(ctrl *gomock.Controller) *MockRemoveAllFS {
	mock := &MockRemoveAllFS{ctrl: ctrl}
	mock.recorder = &MockRemoveAllFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoveAllFS) EXPECT() *MockRemoveAllFSMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRemoveAllFS) Create(ctx context.Context, name string) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRemoveAllFSMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRemoveAllFS)(nil).Create), ctx, name)
}

// Open mocks base method.
func (m *MockRemoveAllFS) Open(ctx context.Context, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockRemoveAllFSMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockRemoveAllFS)(nil).Open), ctx, name)
}

// OpenFile mocks base method.
func (m *MockRemoveAllFS) OpenFile(ctx context.Context, name string, flag int, mode fs.FileMode) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", ctx, name, flag, mode)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockRemoveAllFSMockRecorder) OpenFile(ctx, name, flag, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockRemoveAllFS)(nil).OpenFile), ctx, name, flag, mode)
}

// Remove mocks base method.
func (m *MockRemoveAllFS) Remove(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockRemoveAllFSMockRecorder) Remove(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRemoveAllFS)(nil).Remove), ctx, name)
}

// RemoveAll mocks base method.
func (m *MockRemoveAllFS) RemoveAll(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockRemoveAllFSMockRecorder) RemoveAll(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockRemoveAllFS)(nil).RemoveAll), ctx, name)
}

// MockRenameFS is a mock of RenameFS interface.
type MockRenameFS struct {
	ctrl     *gomock.Controller
	recorder *MockRenameFSMockRecorder
	isgomock struct{}
}

// MockRenameFSMockRecorder is the mock recorder for MockRenameFS.
type MockRenameFSMockRecorder struct {
	mock *MockRenameFS
}

// NewMockRenameFS creates a new mock instance.
func NewMockRenameFS(ctrl *gomock.Controller) *MockRenameFS {
	mock := &MockRenameFS{ctrl: ctrl}
	mock.recorder = &MockRenameFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRenameFS) EXPECT() *MockRenameFSMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRenameFS) Create(ctx context.Context, name string) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRenameFSMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRenameFS)(nil).Create), ctx, name)
}

// Open mocks base method.
func (m *MockRenameFS) Open(ctx context.Context, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockRenameFSMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockRenameFS)(nil).Open), ctx, name)
}

// OpenFile mocks base method.
func (m *MockRenameFS) OpenFile(ctx context.Context, name string, flag int, mode fs.FileMode) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", ctx, name, flag, mode)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockRenameFSMockRecorder) OpenFile(ctx, name, flag, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockRenameFS)(nil).OpenFile), ctx, name, flag, mode)
}

// Remove mocks base method.
func (m *MockRenameFS) Remove(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockRenameFSMockRecorder) Remove(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRenameFS)(nil).Remove), ctx, name)
}

// Rename mocks base method.
func (m *MockRenameFS) Rename(ctx context.Context, oldname, newname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", ctx, oldname, newname)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockRenameFSMockRecorder) Rename(ctx, oldname, newname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockRenameFS)(nil).Rename), ctx, oldname, newname)
}

// MockStatFS is a mock of StatFS interface.
type MockStatFS struct {
	ctrl     *gomock.Controller
	recorder *MockStatFSMockRecorder
	isgomock struct{}
}

// MockStatFSMockRecorder is the mock recorder for MockStatFS.
type MockStatFSMockRecorder struct {
	mock *MockStatFS
}

// NewMockStatFS creates a new mock instance.
func NewMockStatFS(ctrl *gomock.Controller) *MockStatFS {
	mock := &MockStatFS{ctrl: ctrl}
	mock.recorder = &MockStatFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatFS) EXPECT() *MockStatFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockStatFS) Open(ctx context.Context, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockStatFSMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockStatFS)(nil).Open), ctx, name)
}

// Stat mocks base method.
func (m *MockStatFS) Stat(ctx context.Context, name string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", ctx, name)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockStatFSMockRecorder) Stat(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockStatFS)(nil).Stat), ctx, name)
}

// MockReadLinkFS is a mock of ReadLinkFS interface.
type MockReadLinkFS struct {
	ctrl     *gomock.Controller
	recorder *MockReadLinkFSMockRecorder
	isgomock struct{}
}

// MockReadLinkFSMockRecorder is the mock recorder for MockReadLinkFS.
type MockReadLinkFSMockRecorder struct {
	mock *MockReadLinkFS
}

// NewMockReadLinkFS creates a new mock instance.
func NewMockReadLinkFS(ctrl *gomock.Controller) *MockReadLinkFS {
	mock := &MockReadLinkFS{ctrl: ctrl}
	mock.recorder = &MockReadLinkFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadLinkFS) EXPECT() *MockReadLinkFSMockRecorder {
	return m.recorder
}

// Lstat mocks base method.
func (m *MockReadLinkFS) Lstat(ctx context.Context, name string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lstat", ctx, name)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lstat indicates an expected call of Lstat.
func (mr *MockReadLinkFSMockRecorder) Lstat(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lstat", reflect.TypeOf((*MockReadLinkFS)(nil).Lstat), ctx, name)
}

// Open mocks base method.
func (m *MockReadLinkFS) Open(ctx context.Context, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockReadLinkFSMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockReadLinkFS)(nil).Open), ctx, name)
}

// ReadLink mocks base method.
func (m *MockReadLinkFS) ReadLink(ctx context.Context, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadLink", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadLink indicates an expected call of ReadLink.
func (mr *MockReadLinkFSMockRecorder) ReadLink(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadLink", reflect.TypeOf((*MockReadLinkFS)(nil).ReadLink), ctx, name)
}

// MockSymlinkFS is a mock of SymlinkFS interface.
type MockSymlinkFS struct {
	ctrl     *gomock.Controller
	recorder *MockSymlinkFSMockRecorder
	isgomock struct{}
}

// MockSymlinkFSMockRecorder is the mock recorder for MockSymlinkFS.
type MockSymlinkFSMockRecorder struct {
	mock *MockSymlinkFS
}

// NewMockSymlinkFS creates a new mock instance.
func NewMockSymlinkFS(ctrl *gomock.Controller) *MockSymlinkFS {
	mock := &MockSymlinkFS{ctrl: ctrl}
	mock.recorder = &MockSymlinkFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSymlinkFS) EXPECT() *MockSymlinkFSMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSymlinkFS) Create(ctx context.Context, name string) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSymlinkFSMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSymlinkFS)(nil).Create), ctx, name)
}

// Lstat mocks base method.
func (m *MockSymlinkFS) Lstat(ctx context.Context, name string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lstat", ctx, name)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lstat indicates an expected call of Lstat.
func (mr *MockSymlinkFSMockRecorder) Lstat(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lstat", reflect.TypeOf((*MockSymlinkFS)(nil).Lstat), ctx, name)
}

// Open mocks base method.
func (m *MockSymlinkFS) Open(ctx context.Context, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockSymlinkFSMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockSymlinkFS)(nil).Open), ctx, name)
}

// OpenFile mocks base method.
func (m *MockSymlinkFS) OpenFile(ctx context.Context, name string, flag int, mode fs.FileMode) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", ctx, name, flag, mode)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockSymlinkFSMockRecorder) OpenFile(ctx, name, flag, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockSymlinkFS)(nil).OpenFile), ctx, name, flag, mode)
}

// ReadLink mocks base method.
func (m *MockSymlinkFS) ReadLink(ctx context.Context, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadLink", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadLink indicates an expected call of ReadLink.
func (mr *MockSymlinkFSMockRecorder) ReadLink(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadLink", reflect.TypeOf((*MockSymlinkFS)(nil).ReadLink), ctx, name)
}

// Remove mocks base method.
func (m *MockSymlinkFS) Remove(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockSymlinkFSMockRecorder) Remove(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockSymlinkFS)(nil).Remove), ctx, name)
}

// Symlink mocks base method.
func (m *MockSymlinkFS) Symlink(ctx context.Context, oldname, newname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Symlink", ctx, oldname, newname)
	ret0, _ := ret[0].(error)
	return ret0
}

// Symlink indicates an expected call of Symlink.
func (mr *MockSymlinkFSMockRecorder) Symlink(ctx, oldname, newname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Symlink", reflect.TypeOf((*MockSymlinkFS)(nil).Symlink), ctx, oldname, newname)
}

// MockLchownFS is a mock of LchownFS interface.
type MockLchownFS struct {
	ctrl     *gomock.Controller
	recorder *MockLchownFSMockRecorder
	isgomock struct{}
}

// MockLchownFSMockRecorder is the mock recorder for MockLchownFS.
type MockLchownFSMockRecorder struct {
	mock *MockLchownFS
}

// NewMockLchownFS creates a new mock instance.
func NewMockLchownFS(ctrl *gomock.Controller) *MockLchownFS {
	mock := &MockLchownFS{ctrl: ctrl}
	mock.recorder = &MockLchownFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLchownFS) EXPECT() *MockLchownFSMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLchownFS) Create(ctx context.Context, name string) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLchownFSMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLchownFS)(nil).Create), ctx, name)
}

// Lchown mocks base method.
func (m *MockLchownFS) Lchown(ctx context.Context, name, owner, group string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lchown", ctx, name, owner, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lchown indicates an expected call of Lchown.
func (mr *MockLchownFSMockRecorder) Lchown(ctx, name, owner, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lchown", reflect.TypeOf((*MockLchownFS)(nil).Lchown), ctx, name, owner, group)
}

// Lstat mocks base method.
func (m *MockLchownFS) Lstat(ctx context.Context, name string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lstat", ctx, name)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lstat indicates an expected call of Lstat.
func (mr *MockLchownFSMockRecorder) Lstat(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lstat", reflect.TypeOf((*MockLchownFS)(nil).Lstat), ctx, name)
}

// Open mocks base method.
func (m *MockLchownFS) Open(ctx context.Context, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockLchownFSMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockLchownFS)(nil).Open), ctx, name)
}

// OpenFile mocks base method.
func (m *MockLchownFS) OpenFile(ctx context.Context, name string, flag int, mode fs.FileMode) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", ctx, name, flag, mode)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockLchownFSMockRecorder) OpenFile(ctx, name, flag, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockLchownFS)(nil).OpenFile), ctx, name, flag, mode)
}

// ReadLink mocks base method.
func (m *MockLchownFS) ReadLink(ctx context.Context, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadLink", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadLink indicates an expected call of ReadLink.
func (mr *MockLchownFSMockRecorder) ReadLink(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadLink", reflect.TypeOf((*MockLchownFS)(nil).ReadLink), ctx, name)
}

// Remove mocks base method.
func (m *MockLchownFS) Remove(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockLchownFSMockRecorder) Remove(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockLchownFS)(nil).Remove), ctx, name)
}

// Symlink mocks base method.
func (m *MockLchownFS) Symlink(ctx context.Context, oldname, newname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Symlink", ctx, oldname, newname)
	ret0, _ := ret[0].(error)
	return ret0
}

// Symlink indicates an expected call of Symlink.
func (mr *MockLchownFSMockRecorder) Symlink(ctx, oldname, newname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Symlink", reflect.TypeOf((*MockLchownFS)(nil).Symlink), ctx, oldname, newname)
}

// MockTruncateFS is a mock of TruncateFS interface.
type MockTruncateFS struct {
	ctrl     *gomock.Controller
	recorder *MockTruncateFSMockRecorder
	isgomock struct{}
}

// MockTruncateFSMockRecorder is the mock recorder for MockTruncateFS.
type MockTruncateFSMockRecorder struct {
	mock *MockTruncateFS
}

// NewMockTruncateFS creates a new mock instance.
func NewMockTruncateFS(ctrl *gomock.Controller) *MockTruncateFS {
	mock := &MockTruncateFS{ctrl: ctrl}
	mock.recorder = &MockTruncateFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTruncateFS) EXPECT() *MockTruncateFSMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTruncateFS) Create(ctx context.Context, name string) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTruncateFSMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTruncateFS)(nil).Create), ctx, name)
}

// Open mocks base method.
func (m *MockTruncateFS) Open(ctx context.Context, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockTruncateFSMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockTruncateFS)(nil).Open), ctx, name)
}

// OpenFile mocks base method.
func (m *MockTruncateFS) OpenFile(ctx context.Context, name string, flag int, mode fs.FileMode) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", ctx, name, flag, mode)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockTruncateFSMockRecorder) OpenFile(ctx, name, flag, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockTruncateFS)(nil).OpenFile), ctx, name, flag, mode)
}

// Remove mocks base method.
func (m *MockTruncateFS) Remove(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockTruncateFSMockRecorder) Remove(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockTruncateFS)(nil).Remove), ctx, name)
}

// Truncate mocks base method.
func (m *MockTruncateFS) Truncate(ctx context.Context, name string, size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Truncate", ctx, name, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// Truncate indicates an expected call of Truncate.
func (mr *MockTruncateFSMockRecorder) Truncate(ctx, name, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Truncate", reflect.TypeOf((*MockTruncateFS)(nil).Truncate), ctx, name, size)
}

// MockWriteFileFS is a mock of WriteFileFS interface.
type MockWriteFileFS struct {
	ctrl     *gomock.Controller
	recorder *MockWriteFileFSMockRecorder
	isgomock struct{}
}

// MockWriteFileFSMockRecorder is the mock recorder for MockWriteFileFS.
type MockWriteFileFSMockRecorder struct {
	mock *MockWriteFileFS
}

// NewMockWriteFileFS creates a new mock instance.
func NewMockWriteFileFS(ctrl *gomock.Controller) *MockWriteFileFS {
	mock := &MockWriteFileFS{ctrl: ctrl}
	mock.recorder = &MockWriteFileFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriteFileFS) EXPECT() *MockWriteFileFSMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWriteFileFS) Create(ctx context.Context, name string) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWriteFileFSMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWriteFileFS)(nil).Create), ctx, name)
}

// Open mocks base method.
func (m *MockWriteFileFS) Open(ctx context.Context, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockWriteFileFSMockRecorder) Open(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockWriteFileFS)(nil).Open), ctx, name)
}

// OpenFile mocks base method.
func (m *MockWriteFileFS) OpenFile(ctx context.Context, name string, flag int, mode fs.FileMode) (contextual.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", ctx, name, flag, mode)
	ret0, _ := ret[0].(contextual.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockWriteFileFSMockRecorder) OpenFile(ctx, name, flag, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockWriteFileFS)(nil).OpenFile), ctx, name, flag, mode)
}

// Remove mocks base method.
func (m *MockWriteFileFS) Remove(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWriteFileFSMockRecorder) Remove(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWriteFileFS)(nil).Remove), ctx, name)
}

// WriteFile mocks base method.
func (m *MockWriteFileFS) WriteFile(ctx context.Context, name string, data []byte, perm fs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", ctx, name, data, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockWriteFileFSMockRecorder) WriteFile(ctx, name, data, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockWriteFileFS)(nil).WriteFile), ctx, name, data, perm)
}
